import { expect, test } from '@playwright/test'
import { rm } from 'node:fs/promises'

const dataFile = '/tmp/sectrai-finans-e2e.json'
test.beforeEach(async () => { await rm(dataFile, { force: true }) })

test('worker proof, checker approval, sequential unlocking, and reload persistence work end-to-end', async ({ page }) => {
  await page.goto('http://127.0.0.1:4178')
  await expect(page.getByRole('tab', { name: 'KONUŞ' })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'UYGULA' })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'MASA' })).toBeVisible()
  await page.getByRole('tab', { name: 'UYGULA' }).click()
  await expect(page.getByLabel('Finans uygulama tuvali')).toBeVisible()
  await page.getByRole('tab', { name: 'MASA' }).click()
  await expect(page.getByRole('heading', { name: /Hoş geldin/ })).toBeVisible()
  await page.getByRole('button', { name: 'Hesap ve çalışma alanları' }).click()
  await page.getByRole('menuitem', { name: /L3 · Mali Müşavir/ }).click()
  await page.getByRole('button', { name: '↗ İş Akışı' }).click()
  await expect(page.getByRole('heading', { name: 'İş Akışı' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'İncelemeye gönder' }).first()).toBeDisabled()
  await page.locator('input[type=file]').first().setInputFiles({ name: 'mutabakat.pdf', mimeType: 'application/pdf', buffer: Buffer.from('synthetic proof') })
  await page.getByRole('button', { name: 'Kanıtı yükle' }).first().click()
  await expect(page.locator('.notice')).toContainText('hash doğrulamasıyla')
  await page.getByRole('button', { name: 'İncelemeye gönder' }).first().click()
  await expect(page.locator('.notice')).toContainText('checker incelemesine')
  await page.getByRole('button', { name: 'Hesap ve çalışma alanları' }).click()
  await page.getByRole('menuitem', { name: /L2 · Proje Müdürü/ }).click()
  await page.getByRole('button', { name: '↗ İş Akışı' }).click()
  await page.getByRole('button', { name: 'Kanıtı onayla' }).click()
  await expect(page.locator('.notice')).toContainText('bağımlı görevler')
  await page.reload()
  await page.getByRole('tab', { name: 'MASA' }).click()
  await expect(page.getByRole('heading', { name: /Hoş geldin/ })).toBeVisible()
  await page.getByRole('button', { name: 'Hesap ve çalışma alanları' }).click()
  await page.getByRole('menuitem', { name: /L3 · Mali Müşavir/ }).click()
  await page.getByRole('button', { name: '↗ İş Akışı' }).click()
  await expect(page.getByText('Müvekkil takip aksiyonunu kayda al')).toBeVisible()
  await expect(page.getByText('Kanıt bekliyor')).toBeVisible()
  await page.getByRole('button', { name: 'Hesap ve çalışma alanları' }).click()
  await page.getByRole('menuitem', { name: /L1 · Yönetici Ortak/ }).click()
  await expect(page.getByLabel('Serbest çalışma masası')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Kayıtları aç →' }).first()).toBeVisible()
})
